version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Jakarta
    target-branch: dev
    open-pull-requests-limit: 10
    groups:
      runtime:
        dependency-type: production
      development:
        dependency-type: development
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:45"
      timezone: Asia/Jakarta
    target-branch: dev
